server:
  port: 8080

spring:
  webflux:
    base-path: /tecnologia-service
  application:
    name: tecnologia-service
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:tecnologia}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Pragma08679}
  main:
    web-application-type: reactive

management:
  tracing:
    sampling:
      probability: 0.0
    baggage:
      correlation:
        fields:
          - messageId
          - x-message-id
      remote-fields: messageId,x-message-id
  endpoints:
    web:
      exposure:
        include: health, metrics, loggers
      base-path: /
      path-mapping:
        health: actuator/health
        metrics: actuator/metrics
        loggers: tecnologia-service/actuator/loggers
  endpoint:
    health:
      probes:
        enabled: false
      show-details: "always"
  health:
    circuitbreakers:
      enabled: true
    diskspace:
      enabled: false
    r2dbc:
      enabled: true
    ping:
      enabled: false
    refresh:
      enabled: false

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        register-health-indicator: true
    instances:
      tecnologiaDB:
        base-config: default
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
        sliding-window-size: 5
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 25s
        max-wait-duration-in-half-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: false
        record-exceptions: java.util.concurrent.TimeoutException
        ignore-exceptions: com.onclass.tecnologia.domain.exceptions.BusinessException
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 2000ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2.0
        maxWaitDuration: 10000ms
        initialInterval: 500ms
    instances:
      tecnologiaRetry:
        maxAttempts: 5
        waitDuration: 1000ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 1.5
        maxWaitDuration: 10000ms
        initialInterval: 500ms
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 10
        maxWaitDuration: 500ms
    instances:
      tecnologiaBulkhead:
        maxConcurrentCalls: 5
        maxWaitDuration: 1s

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html